// ============================================================================
//  LEARN — per-page teaching content, in English / العربية / हिन्दी.
//  Each string is { en, ar, hi }; the guide renders the language the user picks.
//  `selector` (optional) points at a [data-viz] or CSS selector to spotlight.
//  Language written plain — this is for a store manager, not an analyst.
// ============================================================================
const t = (en, ar, hi) => ({ en, ar, hi });

export const LEARN = {
  landing: {
    title: t("Dashboard", "لوحة القيادة", "डैशबोर्ड"),
    intro: t("Your daily command view. This guide walks through each tile.",
      "عرضك اليومي الرئيسي. يشرح هذا الدليل كل قسم.",
      "आपका दैनिक कमांड व्यू। यह गाइड हर टाइल को समझाता है।"),
    steps: [
      { selector: "[data-viz='landing_head']",
        title: t("The KPI cards", "بطاقات المؤشرات", "KPI कार्ड"),
        body: t("Today at a glance — Net Sales, Orders, AOV and Target. The pill under each shows the change vs last week; hover it for the exact figures and the date compared.",
          "اليوم بلمحة — صافي المبيعات والطلبات ومتوسط قيمة الطلب والهدف. تُظهر الشارة أسفل كل بطاقة التغير مقارنة بالأسبوع الماضي؛ مرّر المؤشر لرؤية الأرقام والتاريخ.",
          "एक नज़र में आज — नेट सेल्स, ऑर्डर, AOV और टारगेट। हर कार्ड के नीचे की पिल पिछले हफ़्ते की तुलना दिखाती है; सटीक आंकड़ों के लिए होवर करें।") },
      { selector: "[data-viz='landing_hourly']",
        title: t("Hourly Sales", "المبيعات بالساعة", "प्रति घंटा बिक्री"),
        body: t("Sales by hour, coloured against a benchmark. Use the Sales/Orders switch and the Yesterday / Last week / 4-wk avg switch. Click any bar to see what drove that hour.",
          "المبيعات حسب الساعة، ملوّنة مقابل مرجع. استخدم مفتاح المبيعات/الطلبات ومفتاح أمس / الأسبوع الماضي / متوسط 4 أسابيع. انقر أي عمود لمعرفة سبب تلك الساعة.",
          "घंटे के हिसाब से बिक्री, एक बेंचमार्क के सामने रंगीन। Sales/Orders और Yesterday / Last week / 4-wk avg स्विच इस्तेमाल करें। किसी बार पर क्लिक कर देखें उस घंटे को किसने चलाया।") },
      { selector: "[data-viz='landing_brand_matrix']",
        title: t("Brand & Source tables", "جداول العلامات والمصادر", "ब्रांड और सोर्स टेबल"),
        body: t("The number broken down by brand and order source, each with WoW/MoM/YoY growth. Click a column header (WoW, AOV…) for its definition in three languages, or to sort.",
          "الرقم مُفصّلاً حسب العلامة ومصدر الطلب، مع نمو أسبوعي/شهري/سنوي. انقر عنوان عمود (WoW، AOV…) لرؤية تعريفه بثلاث لغات أو للترتيب.",
          "ब्रांड और ऑर्डर सोर्स के हिसाब से आंकड़ा, WoW/MoM/YoY ग्रोथ के साथ। कॉलम हेडर (WoW, AOV…) पर क्लिक कर तीन भाषाओं में परिभाषा देखें या सॉर्ट करें।") },
      { selector: null,
        title: t("Customise", "التخصيص", "कस्टमाइज़"),
        body: t("Any tile can be moved, resized or hidden. Your layout saves to your account; the default is one click away.",
          "يمكن نقل أي قسم أو تغيير حجمه أو إخفاؤه. يُحفظ تخطيطك في حسابك؛ والافتراضي على بُعد نقرة.",
          "कोई भी टाइल हिलाई, आकार बदली या छिपाई जा सकती है। आपका लेआउट आपके अकाउंट में सेव होता है; डिफ़ॉल्ट एक क्लिक दूर है।") },
    ],
  },
  overview: {
    title: t("Sales Analysis", "تحليل المبيعات", "सेल्स एनालिसिस"),
    intro: t("The deep-dive report, told as a story: When, Where, How, How much.",
      "تقرير التحليل المعمّق، مُروى كقصة: متى، أين، كيف، كم.",
      "गहन रिपोर्ट, एक कहानी की तरह: कब, कहाँ, कैसे, कितना।"),
    steps: [
      { selector: ".sa-sec-n",
        title: t("Four questions", "أربعة أسئلة", "चार सवाल"),
        body: t("The numbered sections answer one question each — When we sell, Where, How (channels) and How much (ticket). Read in order for the full picture.",
          "تجيب الأقسام المرقّمة عن سؤال واحد لكل قسم — متى نبيع، أين، كيف (القنوات)، وكم (قيمة الطلب). اقرأها بالترتيب للصورة الكاملة.",
          "क्रमांकित सेक्शन एक-एक सवाल का जवाब देते हैं — कब बेचते हैं, कहाँ, कैसे (चैनल), कितना (टिकट)। पूरी तस्वीर के लिए क्रम में पढ़ें।") },
      { selector: "[data-viz='ov_loc_day']",
        title: t("Location × Day heatmap", "خريطة الفرع × اليوم", "लोकेशन × दिन हीटमैप"),
        body: t("Every branch against every weekday. Darker = busier. Switch between Sales, Orders and AOV. Use it for staffing — which branch is busy on which day.",
          "كل فرع مقابل كل يوم من الأسبوع. الأغمق = أكثر ازدحاماً. بدّل بين المبيعات والطلبات ومتوسط قيمة الطلب. استخدمها للجدولة.",
          "हर ब्रांच बनाम हर सप्ताह-दिन। गहरा = ज़्यादा व्यस्त। Sales, Orders, AOV के बीच बदलें। स्टाफिंग के लिए इस्तेमाल करें।") },
      { selector: "[data-viz='ov_heatmap']",
        title: t("Peak windows", "أوقات الذروة", "पीक विंडो"),
        body: t("Hour × weekday — the darkest cells are your busiest trading windows. Each cell shows the figure; hover for the exact value.",
          "الساعة × يوم الأسبوع — الخلايا الأغمق هي أوقات ذروتك. تُظهر كل خلية الرقم؛ مرّر المؤشر للقيمة الدقيقة.",
          "घंटा × सप्ताह-दिन — सबसे गहरी सेल आपकी सबसे व्यस्त विंडो हैं। हर सेल आंकड़ा दिखाती है; सटीक मान के लिए होवर करें।") },
      { selector: null,
        title: t("Filter by clicking", "التصفية بالنقر", "क्लिक कर फ़िल्टर"),
        body: t("Click a branch, brand or channel in any chart and the whole page filters to it. Click again to clear. It never reloads.",
          "انقر فرعاً أو علامة أو قناة في أي رسم بياني لتصفية الصفحة كاملة. انقر مرة أخرى للمسح. لا تُعاد الصفحة أبداً.",
          "किसी चार्ट में ब्रांच, ब्रांड या चैनल पर क्लिक करें, पूरा पेज उसी पर फ़िल्टर हो जाएगा। साफ़ करने को फिर क्लिक करें।") },
    ],
  },
  compare: {
    title: t("Compare", "المقارنة", "तुलना"),
    intro: t("Compare any two periods and understand not just what changed, but why.",
      "قارن أي فترتين وافهم ليس فقط ما تغيّر، بل لماذا.",
      "किन्हीं दो अवधियों की तुलना करें और समझें कि क्या बदला और क्यों।"),
    steps: [
      { selector: ".cmp-cc",
        title: t("Command Center", "مركز التحكم", "कमांड सेंटर"),
        body: t("The sticky bar always shows exactly what's being compared — the two periods, day counts, comparison quality and filters. Change the dates here.",
          "يُظهر الشريط الثابت دائماً ما تتم مقارنته — الفترتان وعدد الأيام وجودة المقارنة والمرشحات. غيّر التواريخ من هنا.",
          "स्टिकी बार हमेशा दिखाता है कि क्या तुलना हो रही है — दो अवधियाँ, दिनों की गिनती, तुलना गुणवत्ता और फ़िल्टर। तारीखें यहीं बदलें।") },
      { selector: ".cmp-cc-actions",
        title: t("Align to occasion", "المحاذاة حسب المناسبة", "अवसर से संरेखित करें"),
        body: t("For Eid, Ramadan or a campaign, use 'Align to occasion' — it lines up Day 1 vs Day 1 across years instead of matching calendar dates.",
          "لعيد أو رمضان أو حملة، استخدم 'المحاذاة حسب المناسبة' — يحاذي اليوم 1 مقابل اليوم 1 عبر السنوات بدلاً من مطابقة التواريخ.",
          "ईद, रमज़ान या किसी कैंपेन के लिए 'Align to occasion' इस्तेमाल करें — यह कैलेंडर तारीख़ के बजाय Day 1 बनाम Day 1 मिलाता है।") },
      { selector: ".cmp-narr",
        title: t("What the numbers say", "ماذا تقول الأرقام", "आंकड़े क्या कहते हैं"),
        body: t("A written summary from the calculated results. Facts are stated plainly; anything unproven is tagged 'Hypothesis'. It never invents a cause.",
          "ملخص مكتوب من النتائج المحسوبة. تُذكر الحقائق بوضوح؛ وأي شيء غير مؤكد يُوسم بـ 'فرضية'. لا يختلق سبباً أبداً.",
          "गणना किए नतीजों से लिखित सारांश। तथ्य साफ़ बताए जाते हैं; अप्रमाणित चीज़ 'Hypothesis' टैग होती है। यह कभी कारण नहीं गढ़ता।") },
      { selector: "[data-viz-label='Growth Bridge']",
        title: t("Growth bridge", "جسر النمو", "ग्रोथ ब्रिज"),
        body: t("The waterfall shows how Period B sales became Period A sales, step by step. Every component reconciles exactly — no hidden residual.",
          "يُظهر الشلال كيف أصبحت مبيعات الفترة ب مبيعات الفترة أ خطوة بخطوة. كل مكوّن يتطابق تماماً — بلا بواقٍ خفية.",
          "वॉटरफ़ॉल दिखाता है कि Period B की बिक्री कदम-दर-कदम Period A कैसे बनी। हर घटक ठीक मिलान करता है — कोई छिपा शेष नहीं।") },
      { selector: null,
        title: t("Like-for-Like & partial days", "المثل بالمثل والأيام الجزئية", "लाइक-फॉर-लाइक और आंशिक दिन"),
        body: t("Turn on 'Like-for-Like only' for just the branches trading in both periods. If Period A ends on an incomplete day, a one-click fix compares both to the same hour.",
          "فعّل 'المثل بالمثل فقط' لعرض الفروع العاملة في الفترتين فقط. إذا انتهت الفترة أ بيوم غير مكتمل، فإصلاح بنقرة يقارن الاثنين حتى الساعة نفسها.",
          "'Like-for-Like only' चालू करें ताकि सिर्फ़ दोनों अवधियों में चलने वाली ब्रांच दिखें। अगर Period A अधूरे दिन पर खत्म हो, एक-क्लिक फ़िक्स दोनों को एक ही घंटे तक तुलना करता है।") },
      { selector: ".cmp-cc-actions",
        title: t("Share & Present", "المشاركة والعرض", "शेयर और प्रेज़ेंट"),
        body: t("The whole comparison lives in the URL — Share copies a link that reopens this exact view. Present opens a full-screen deck for meetings.",
          "المقارنة كاملة موجودة في الرابط — المشاركة تنسخ رابطاً يعيد فتح هذا العرض بالضبط. العرض يفتح شرائح ملء الشاشة للاجتماعات.",
          "पूरी तुलना URL में है — Share एक लिंक कॉपी करता है जो यही व्यू खोलता है। Present मीटिंग के लिए फ़ुल-स्क्रीन डेक खोलता है।") },
    ],
  },
  operations: {
    title: t("Operations", "العمليات", "ऑपरेशंस"),
    intro: t("Operational health — prep time, delivery, complaints and offline rate, by store.",
      "صحة العمليات — وقت التحضير والتوصيل والشكاوى ونسبة عدم الاتصال، حسب المتجر.",
      "ऑपरेशनल हेल्थ — प्रेप टाइम, डिलीवरी, शिकायतें और ऑफ़लाइन रेट, स्टोर के हिसाब से।"),
    steps: [
      { selector: "[data-viz='ops_kpis']",
        title: t("Health gauges", "مقاييس الصحة", "हेल्थ गेज"),
        body: t("The five gauges are your operational vital signs. For all of these, lower is better — a falling number is good news.",
          "المقاييس الخمسة هي علاماتك الحيوية التشغيلية. لكلها، الأقل أفضل — الرقم المنخفض خبر جيد.",
          "पाँच गेज आपके ऑपरेशनल वाइटल हैं। इन सबके लिए कम बेहतर है — गिरता आंकड़ा अच्छी खबर है।") },
      { selector: null,
        title: t("Targets & shortfall", "الأهداف والعجز", "टारगेट और कमी"),
        body: t("Where targets are set, each metric shows how far above or below target the store is running. Ops Directors and Admins set these.",
          "حيث تُحدَّد الأهداف، يُظهر كل مؤشر مدى ارتفاع أو انخفاض المتجر عن الهدف. يحددها مديرو العمليات والمشرفون.",
          "जहाँ टारगेट सेट हैं, हर मेट्रिक दिखाता है स्टोर टारगेट से कितना ऊपर या नीचे है। इन्हें Ops Director और Admin सेट करते हैं।") },
    ],
  },
  productmix: {
    title: t("Product Mix", "مزيج المنتجات", "प्रोडक्ट मिक्स"),
    intro: t("What's actually selling — heroes, categories, day-parts and cross-sell.",
      "ما الذي يُباع فعلاً — الأصناف الأبطال والفئات وأوقات اليوم والبيع المتقاطع.",
      "असल में क्या बिक रहा है — हीरो, कैटेगरी, डे-पार्ट और क्रॉस-सेल।"),
    steps: [
      { selector: ".pm-filters",
        title: t("Filter bar", "شريط التصفية", "फ़िल्टर बार"),
        body: t("The top bar filters every visual by product, category, order source or location. Source and Location come from the order, not the line item.",
          "يصفّي الشريط العلوي كل رسم حسب المنتج أو الفئة أو مصدر الطلب أو الموقع. المصدر والموقع من الطلب، لا من بند الصنف.",
          "ऊपरी बार हर विज़ुअल को प्रोडक्ट, कैटेगरी, ऑर्डर सोर्स या लोकेशन से फ़िल्टर करता है। सोर्स और लोकेशन ऑर्डर से आते हैं, लाइन आइटम से नहीं।") },
      { selector: null,
        title: t("Cross-Sell & Attach", "البيع المتقاطع والإرفاق", "क्रॉस-सेल और अटैच"),
        body: t("Pick a main item to see what's bought alongside it. Use this to design combos and prompts.",
          "اختر صنفاً رئيسياً لرؤية ما يُشترى معه. استخدمها لتصميم العروض والاقتراحات.",
          "एक मुख्य आइटम चुनें और देखें उसके साथ क्या खरीदा जाता है। इससे कॉम्बो और प्रॉम्प्ट डिज़ाइन करें।") },
    ],
  },
  runrate: {
    title: t("Sales Run Rate", "معدل تشغيل المبيعات", "सेल्स रन रेट"),
    intro: t("Where the month is heading if the current pace holds.",
      "إلى أين يتجه الشهر إذا استمر المعدل الحالي.",
      "अगर मौजूदा गति बनी रहे तो महीना कहाँ जा रहा है।"),
    steps: [
      { selector: "[data-viz='rr_kpis']",
        title: t("The rate cards", "بطاقات المعدلات", "रेट कार्ड"),
        body: t("MRR, DRR, RRR and the rest project the month-end total. Click any of these terms' headers for a plain-language definition in three languages.",
          "MRR وDRR وRRR وغيرها تتوقع إجمالي نهاية الشهر. انقر عنوان أي مصطلح لتعريف واضح بثلاث لغات.",
          "MRR, DRR, RRR वगैरह महीने-अंत कुल का अनुमान लगाते हैं। किसी टर्म हेडर पर क्लिक कर तीन भाषाओं में परिभाषा देखें।") },
      { selector: "[data-viz='rr_daily']",
        title: t("The runrate line", "خط معدل التشغيل", "रनरेट लाइन"),
        body: t("The chart tracks actual against target and the required run-rate to hit the month. Below the required line means you're behind plan.",
          "يتتبع الرسم الفعلي مقابل الهدف والمعدل المطلوب لتحقيق الشهر. تحت الخط المطلوب يعني أنك متأخر عن الخطة.",
          "चार्ट एक्चुअल को टारगेट और महीने के लिए ज़रूरी रन-रेट के सामने ट्रैक करता है। ज़रूरी लाइन से नीचे मतलब आप प्लान से पीछे हैं।") },
    ],
  },
  locations: {
    title: t("Locations", "المواقع", "स्थान"),
    intro: t("Every branch on a map, plus a per-store scorecard — all scoped to the date and brand you pick at the top.",
      "كل فرع على الخريطة، مع بطاقة أداء لكل متجر — الكل ضمن التاريخ والعلامة المختارة بالأعلى.",
      "नक्शे पर हर ब्रांच, साथ में हर स्टोर का स्कोरकार्ड — ऊपर चुनी तारीख़ और ब्रांड के अनुसार।"),
    steps: [
      { selector: null, title: t("The map", "الخريطة", "नक्शा"),
        body: t("Each pin is a store. Bubble size = sales, colour = brand. Zoom, pan, and tap a pin to see that branch's sales, orders and average check.",
          "كل علامة متجر. حجم الدائرة = المبيعات، اللون = العلامة. كبّر وحرّك وانقر علامة لرؤية مبيعات الفرع وطلباته ومتوسط قيمته.",
          "हर पिन एक स्टोर। बबल आकार = बिक्री, रंग = ब्रांड। ज़ूम, पैन करें और पिन टैप कर उस ब्रांच की बिक्री, ऑर्डर व औसत चेक देखें।") },
      { selector: null, title: t("Store scorecard", "بطاقة أداء المتاجر", "स्टोर स्कोरकार्ड"),
        body: t("The table ranks every branch by sales with orders, AOV, prep, delivery and rating — sortable, and always filtered to your selection.",
          "يرتّب الجدول كل فرع حسب المبيعات مع الطلبات ومتوسط القيمة ووقت التحضير والتوصيل والتقييم — قابل للترتيب.",
          "टेबल हर ब्रांच को बिक्री से रैंक करती है — ऑर्डर, AOV, प्रेप, डिलीवरी और रेटिंग सहित; सॉर्ट किया जा सकता है।") },
    ],
  },
  analysislab: {
    title: t("Analysis Lab", "مختبر التحليل", "एनालिसिस लैब"),
    intro: t("A free-form explorer: pick the dimensions and measure you want and the Lab builds the breakdown live from the model.",
      "مستكشف حر: اختر الأبعاد والمقياس الذي تريده ويبني المختبر التحليل مباشرةً من النموذج.",
      "फ्री-फॉर्म एक्सप्लोरर: अपनी पसंद के डाइमेंशन और मेज़र चुनें, लैब मॉडल से लाइव ब्रेकडाउन बनाता है।"),
    steps: [
      { selector: null, title: t("Pick what to slice by", "اختر التقسيم", "किससे स्लाइस करें चुनें"),
        body: t("Choose dimensions — brand, location, channel, day, category — and a measure like Net Sales, Orders or AOV. Results respect your date and brand filter and your data access.",
          "اختر الأبعاد — العلامة، الموقع، القناة، اليوم، الفئة — ومقياساً مثل صافي المبيعات أو الطلبات أو متوسط القيمة. تحترم النتائج تاريخك وعلامتك وصلاحياتك.",
          "डाइमेंशन चुनें — ब्रांड, लोकेशन, चैनल, दिन, कैटेगरी — और नेट सेल्स/ऑर्डर/AOV जैसा मेज़र। नतीजे आपकी तारीख़, ब्रांड और एक्सेस के अनुसार होते हैं।") },
      { selector: null, title: t("Go deeper, then export", "تعمّق ثم صدّر", "गहराई में जाएँ, फिर एक्सपोर्ट"),
        body: t("Add or drop a dimension to drill in or zoom out. Any table can be exported to Excel for sharing.",
          "أضف أو أزل بُعداً للتعمق أو التوسّع. يمكن تصدير أي جدول إلى Excel للمشاركة.",
          "ड्रिल-इन या ज़ूम-आउट के लिए डाइमेंशन जोड़ें/हटाएँ। कोई भी टेबल Excel में एक्सपोर्ट की जा सकती है।") },
    ],
  },
};

export const LEARN_LANGS = [{ k: "en", label: "EN" }, { k: "ar", label: "ع" }];
export const learnFor = (page) => LEARN[page] || null;
